export const actionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SET_ERROR: 'SET_ERROR',
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    PLUS_AMOUNT: 'PLUS_AMOUNT',
    MINUS_AMOUNT: 'MINUS_AMOUNT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    ADD_TO_FAVORITE : 'ADD_TO_FAVORITE',
    DELETE_FAVORITE : 'DELETE_FAVORITE',
    UPDATE_FAVORITE :  "UPDATE_FAVORITE",
    UPDATE_DATE : "UPDATE_DATE",

};